package edu.gmu.cs321;

import java.sql.*;

//import com.mysql.cj.protocol.Resultset;

public class TestDatabase {
    // JDBC URL, username, and password of MySQL server
    private static final String URL = "jdbc:mysql://localhost:3306/cs321";
    private static final String USER = "root";
    private static final String PASSWORD = "Montanorios12"; // replace with your MySQL password

    // JDBC variables for opening, closing connection and statement
    private static Connection connection;
    private static Statement statement;

    // Method to establish connection
    public static Connection getConnection() {
        try {
            // Load and register MySQL driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
            return connection;
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    // Method to create a new user
    public static int createImmigrant(String first, String last, Date dob) {
        // id is autogenerated by the database as I configured the primary key with "AI"
        // in MySQL Workbench UI
        String insertQuery = "insert into immigrant (first, last, dob) VALUES (?, ?, ?)";
        int id = 0;
        try {
            Connection conn = getConnection();
            PreparedStatement stmt = conn.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS);
            stmt.setString(1, first);
            stmt.setString(2, last);
            stmt.setDate(3, dob);
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Immigrant added successfully.");
                ResultSet rs = stmt.getGeneratedKeys();
                if (rs.next())
                    id = rs.getInt(1);
            } else {
                System.out.println("Error adding immigrant.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return id;
    }

    // Method to select all users from the database
    public static void selectImmigrants() {
        String selectQuery = "SELECT * FROM Immigrant";

        try (Connection conn = getConnection();
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(selectQuery)) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String first = rs.getString("first");
                String last = rs.getString("last");
                String dob = rs.getString("dob");
                System.out.println("ID: " + id + ", First: " + first + ", Last: " + last + ", DOB: " + dob);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Method to update a user's email based on user ID
    public static void updateImmigrant(int userId, String first, String last) {
        String updateQuery = "UPDATE immigrant SET first = ?, last = ? WHERE id = ?";

        try (Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(updateQuery)) {

            stmt.setString(1, first);
            stmt.setString(2, last);
            stmt.setInt(3, userId);
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("User updated successfully.");
            } else {
                System.out.println("User not found.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        // Create new users
        // createImmigrant(106, "First John", "First Doe", Date.valueOf("2003-01-01"));
        int id = createImmigrant("Kellie", "Mayham", Date.valueOf("1999-12-01"));
        System.out.println("New Immigrant ID: " + id);

        // Select and display all users
        System.out.println("All users in the database:");
        selectImmigrants();

        // Update user's email
        updateImmigrant(110, "New Guy", "New Who");

        // Select and display all users after update
        // System.out.println("All users after update:");
        selectImmigrants();
    }

}
